# Generated by Django 4.2 on 2023-04-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_vote_unique_together_alter_vote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hexa',
            field=models.CharField(default='#FFF', max_length=7),
        ),
    ]
