# Generated by Django 4.2 on 2023-04-11 15:33

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_color_hexa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hexa',
            field=colorfield.fields.ColorField(default='#FFF', image_field=None, max_length=7, samples=None),
        ),
    ]
